package com.psp.npci.adapter.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the inbound Kafka event published by the Orchestrator on topic
 * {@code npci.outbound.request}. The Adapter consumes this event and triggers
 * the appropriate outbound NPCI call.
 *
 * <p>
 * JSON shape:
 * 
 * <pre>
 * {
 *   "txnId":     "uuid",
 *   "msgId":     "uuid",
 *   "type":      "PAY" | "BALANCE",
 *   "payerVpa":  "user@demopsp",
 *   "payeeVpa":  "merchant@okaxis",
 *   "amount":    "500.00",
 *   "timestamp": "2026-04-18T10:30:00Z"
 * }
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class NpciOutboundRequestEvent {

    /**
     * Unique transaction identifier (UUID). Used as Redis partition key and NPCI
     * txnId.
     */
    private String txnId;

    /**
     * Message identifier generated by Orchestrator (UUID). Echoed back in the
     * response.
     */
    private String msgId;

    /**
     * Transaction type.
     * <ul>
     * <li>{@code PAY} — PSP-initiated debit (async, callback via RespPay)</li>
     * <li>{@code BALANCE} — Balance enquiry (synchronous, result in HTTP
     * response)</li>
     * </ul>
     */
    private String type;

    /** Payer UPI VPA, e.g. {@code user@demopsp}. */
    private String payerVpa;

    /** Payee UPI VPA, e.g. {@code merchant@okaxis}. Null for BALANCE requests. */
    private String payeeVpa;

    /** Transaction amount as a decimal string, e.g. {@code "500.00"}. */
    private String amount;

    /** ISO-8601 UTC timestamp when the Orchestrator initiated the event. */
    private String timestamp;
}
