spring:
  application:
    name: cbs-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest

cbs:
  debit:
    db:
      url: ${DEBIT_DB_URL:jdbc:postgresql://localhost:5433/cbs_debit}
  credit:
    db:
      url: ${CREDIT_DB_URL:jdbc:postgresql://localhost:5434/cbs_credit}
  db:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres123}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.hpe.upi: INFO
