server:
  port: 8083

spring:
  application:
    name: npci-response-adapter
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: npci-response-adapter-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

kafka:
  topic:
    npci-response: upi.bank.npci.response

npci:
  callback-url: ${NPCI_CALLBACK_URL:http://localhost:8080/upi/callback}
